title: Disciplinas
email: antonio.dias@ifpb.edu.br
description: >- # this means to ignore newlines until "baseurl:"
  Site das disciplinas ministradas pelo professor Antonio Júnior
  no IFPB, campus Esperança.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://antoniojnr.github.io"

twitter_username: addsjunior
github_username: antoniojnr

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

toc: false
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
